### ISSUE TITLE
when will you provide dog keypoint prediction code

### ISSUE THREAD

**Issue by sunbin1357** [benjiebob/SMALify#20]
when will you provide dog keypoint prediction code

**Comment by benjiebob** [comment]
Unfortunately, releasing specific code for our paper [Creatures Great and SMAL](https://arxiv.org/abs/1811.05804) is nontrivial due to terms in my PhD sponsorship. This is something I will look at doing, but this is not my current priority (my thesis is due soon!). 

However, if you are just in need of a trained dog keypoint predictor, you can train (for example) HourglassNet on the [StanfordExtra](https://github.com/benjiebob/StanfordExtra) dataset. We are planning to release a pretrained model for this soon -- tagging @OllieBoyne for his awareness on this.

**Comment by sunbin1357** [comment]
I haven't looked at StanfordExtra dataset yet. Is it in the same format as Human3.6m or COCO?
